### ISSUE TITLE
MDNS message length limited to 550

### ISSUE THREAD

**Issue by Zuroy** [TrippyLighting/EthernetBonjour#20]
When trying to register a service with TXT record if the message length exceeds 550 the packet results to be malformed (using wireshark) .
I tried to search inside the code where this "maximum length" could be declared but I did not find anything.

**Comment by DeltaCore** [comment]
Can you provide some source code so we can reproduce the issue? What board are you using?

**Comment by Zuroy** [comment]
I'm using the Portenta H7 board. The library works perfectly with messages not longer than 550. The code is the same as the example provided and works flawlessly with shorter messages.

**Comment by Zuroy** [comment]
To solve this problem it is necessary to change LINE 30 of MbedUdp.h to increase the size. 
More details here: [https://forum.arduino.cc/t/ethernetbonjour-mdns-message-length-limited-to-550/911968/2](url)
